//
// Created by sidahmedlahmer on 3/19/19.
//

#ifndef HAZARDOUS_MATERIALS_CLIENTMESSAGE_H
#define HAZARDOUS_MATERIALS_CLIENTMESSAGE_H

namespace network{
class ClientMessage {



public:
    enum CLIENT_MESSAGE_TYPE{
        LOGIN,REGISTER,ADD_ENGINE,SHOT,CHAT_C,MOVE,SKIP_TURN,CREATE_GAME,JOIN_GAME,MUTE_CHAT
    };

};

}


#endif //HAZARDOUS_MATERIALS_CLIENTMESSAGE_H
