#ifndef DEF_ENUM
#define DEF_ENUM

enum SQUARE_TYPE
{
    NONE,
    ENGINE_MOTOR,
    ENGINE_MOTOR_DESACTIVATED,
    ENGINE_WEAPON,
    ENGINE_WEAPON_DESACTIVATED,
    ENGINE_PART,
    ENGINE_DEAD
};

enum ENGINE_TYPE
{
    PORTE_AVION,
    CROISEUR,
    CONTRE_TORPILLEUR,
    CUIRASSE,
    TORPILLEUR,
    BOMBARDIER,
    INTERCEPTEUR,
    BROUILLEUR,
    PATROUILE,
    RECONNAISSANCE
};

enum SHOT_TYPE
{
    PORTE_AVION_SKILL,
    CROISEUR_SKILL,
    CONTRE_TORPILLEUR_SKILL,
    CUIRASSE_SKILL,
    TORPILLEUR_SKILL,
    BOMBARDIER_SKILL,
    INTERCEPTEUR_SKILL,
    BROUILLEUR_SKILL,
    PATROUILE_SKILL,
    RECONNAISSANCE_SKILL
};


#endif
