//
// Created by stevlulz on 3/7/19.
//

#ifndef TMP_PROJ_ENUM_H
#define TMP_PROJ_ENUM_H

enum SQUARE_TYPE
{
    NONE,
    ENGINE_MOTOR,
    ENGINE_WEAPON,
    ENGINE_PART,
    ENGINE_MOTOR_DESACTIVATED,
    ENGINE_WEAPON_DESACTIVATED,
    ENGINE_MOTOR_DEAD,
    ENGINE_WEAPON_DEAD,
    ENGINE_PART_DEAD
};

enum MOTOR_STATE
{
    MOTOR,
    MOTOR_DESACTIVATED,
    MOTOR_DEAD
};

enum WEAPON_STATE
{
    WEAPON,
    WEAPON_DESACTIVATED,
    WEAPON_DEAD
};

enum ENGINE_TYPE
{
    PORTE_AVION,
    CROISEUR,
    CONTRE_TORPILLEUR,
    CUIRASSE,
    TORPILLEUR,
    BOMBARDIER,
    INTERCEPTEUR,
    BROUILLEUR,
    PATROUILE,
    RECONNAISSANCE
};

enum SHOT_TYPE
{
    PORTE_AVION_SKILL,
    CROISEUR_SKILL,
    CONTRE_TORPILLEUR_SKILL,
    CUIRASSE_SKILL,
    TORPILLEUR_SKILL,
    BOMBARDIER_SKILL,
    INTERCEPTEUR_SKILL,
    BROUILLEUR_SKILL,
    PATROUILE_SKILL,
    RECONNAISSANCE_SKILL
};


#endif //TMP_PROJ_ENUM_H
